services:
  - type: web
    name: storyforge-ai
    runtime: node
    plan: starter
    region: frankfurt # or oregon / ohio
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
